name: Approve Deployment
run-name: Approve Deployment

on:
  workflow_dispatch:
  pull_request:
    
jobs:
  terraform: 
    name: Run Terraform
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        environment:
        - staging
        - production
    
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        
      - name: Run for ${{ matrix.environment }}
        uses: ./.github/workflows/terraform.yml
        with:
          environment: ${{ matrix.environment }}