name: Approve Deployment
run-name: Approve Deployment

on:
  workflow_dispatch:
  pull_request:
    
jobs:
  terraform: 
    name: Run Terraform
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        environment:
        - staging
        - production
    
    steps:
      - name: Run for ${{ matrix.environment }}
        uses: .github/workflows/terraform.yaml
        with:
          environment: ${{ matrix.environment }}