name: Approve Deployment
run-name: Approve Deployment

on:
  workflow_dispatch:
  pull_request:
    
jobs:
  terraform: 
    name: Run Terraform

    strategy:
      fail-fast: false
      matrix:
        environment:
        - staging
        - production

    uses: ./.github/workflows/terraform.yml
    with:
      environment: ${{ matrix.environment }}