name: Artifact test

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Store
      uses: actions/upload-artifact@v3
      with:
        name: file
        path: README.md

  download:
    runs-on: ubuntu-latest
    
    steps:
    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: file
        path: .

    - run: cat README.md
