name: Docker GHA Inspect
on:
  workflow_dispatch:


jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: |
          docker version

      - run: |
          docker info

      - run: |
          docker buildx version 