name: Empty matrix

on:
  workflow_dispatch:
    inputs:
      list:
        description: 'Spaces separated string'

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      TEST: ""
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"       
      - name: Generate matrix
        id: matrix
        run: |
          json=$( go run .github/helpers/generate-list.go ${{ inputs.list }} )
          echo "matrix=$json" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: needs.job1.outputs.matrix != '[]'
    strategy:
      matrix: 
        list: ${{ fromJson(needs.job1.outputs.matrix) }}
    steps:
      - name: Echo list element
        run: |
          echo ${{ matrix.list }}

  job3: 
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Echo list element
        run: |
            echo "hello"