name: Exit early demo

on:
  workflow_dispatch:
    inputs:
      list:
        description: 'Spaces separated string'
        
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      TEST: ""
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - name: Generate matrix
        id: matrix
        run: |
          json=$( go run .github/helpers/generate-images-list.go )
          echo "matrix=$json" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    needs: job1
    strategy:
      matrix: 
        list: ${{ fromJson(needs.job1.outputs.matrix) }}
    steps:
      - name: Echo list element
        run: |
          echo ${{ matrix.list }}