name: Terraform
run-name: Terraform run for ${{ inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment/workdir name"
        type: choice
        options:
          - staging
          - production
          - development
        default: staging
        required: true
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

jobs:
  plan:
    defaults:
      run:
        working-directory: environments/${{ inputs.environment }}
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color --out tf_plan.out
      continue-on-error: true
      
    - uses: actions/upload-artifact@v3
      name: Upload plan
      with:
        name: tf_plan_${{ inputs.environment }}
        path: environments/${{ inputs.environment }}/tf_plan.out
        retention-days: 1

    - name: Set summary
      run: |
        cat <<EOF >> $GITHUB_STEP_SUMMARY
        ## Terraform Environment - \`${{ inputs.environment }}\`
        #### Terraform Initialization - ⚙️\`${{ steps.init.outcome }}\`
        #### Terraform Validation - 🤖\`${{ steps.validate.outcome }}\`

        <details><summary>Validation Output</summary>

        \`\`\`
        ${{ steps.validate.outputs.stdout }}
        \`\`\`

        </details>

        #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

        <details><summary>Show Plan</summary>

        \`\`\`
        ${{steps.plan.outputs.stdout}}
        \`\`\`

        </details>
        EOF

      
    - uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      env:
        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          // 1. Retrieve existing bot comments for the PR
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          })
          const botComment = comments.find(comment => {
            return comment.user.type === 'Bot' && comment.body.includes('Terraform Format and Style') && comment.body.includes('Terraform Environment \`${{ inputs.environment }}\`')
          })

          // 2. Prepare format of the comment
          const output = `
          #### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
          #### Terraform Environment \`${{ inputs.environment }}\`
          #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
          #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
          <details><summary>Validation Output</summary>

          \`\`\`\n
          ${{ steps.validate.outputs.stdout }}
          \`\`\`

          </details>

          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

          <details><summary>Show Plan</summary>

          \`\`\`
          ${process.env.PLAN}
          \`\`\`

          </details>

          Summary: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
          

          // 3. If we have a comment, update it, otherwise create a new one
          if (botComment) {
            github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: output
            })
          } else {
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
          }

  wait-for-approval:
    permissions:
      issues: write
    needs:
      - plan
    runs-on: ubuntu-latest
    steps:
      - uses: trstringer/manual-approval@v1
        timeout-minutes: 60
        if: inputs.environment == 'development'
        with:
          secret: ${{ github.TOKEN }}
          approvers: krzwiatrzyk
          minimum-approvals: 1
          issue-title: "Deploying ${{ inputs.environment }}"
          issue-body: "Please approve or deny the deployment of ${{ inputs.environment }}"
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''

  apply:
    needs:
    - plan
    - wait-for-approval
    if: github.event_name != 'pull_request'
    environment: ${{ inputs.environment }}

    concurrency: ${{ inputs.environment }}
    # concurrency:
    #   group: ${{ inputs.environment }}
    #   cancel-in-progress: true

    defaults:
      run:
        working-directory: environments/${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      id: init
      run: terraform init

    - uses: actions/download-artifact@v3
      name: Download plan
      with:
        name: tf_plan_${{ inputs.environment }}
        path: environments/${{ inputs.environment }}

    - name: Terraform Apply
      id: plan
      run: terraform apply tf_plan.out
      continue-on-error: true