name: Groups

on:
  workflow_dispatch:
    inputs:
        environment:
            type: string

jobs:
    plan:
      runs-on: ubuntu-latest
      concurrency: ${{ format('refs/heads/{0}', github.event.repository.default_branch) == github.ref && inputs.environment || github.run_id }}
      steps:
      - run: |
          echo ${{ github.event.repository.default_branch }} ${{ github.ref }} ${{ format('plan_{0}', inputs.environment) }}
          sleep 60
          echo Hey

    apply:
        needs:
            - plan
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}
        concurrency: ${{ format('refs/heads/{0}', github.event.repository.default_branch) == github.ref && inputs.environment || github.run_id }}
        steps:
        - run: |
            sleep 120
            echo Hey