name: Test job dependency 

on:
  workflow_dispatch:
    inputs:
      job1_run:
        type: boolean
        default: true
      job1_exit_code:
        type: number
        default: 0

jobs:
  job1:
    runs-on: ubuntu-latest
    if: inputs.job1_run
    steps:
      - name: Step1
        run: exit ${{ inputs.job1_exit_code }}

  job2:
    runs-on: ubuntu-latest
    if: always() && (needs.job1.result == 'success' || needs.job1.result == 'skipped')
    needs:
    - job1
    steps:
      - name: Step1
        run: echo job2

  job3:
    runs-on: ubuntu-latest
    needs:
    - job2
    steps:
      - name: Step1
        run: echo job2