name: Comment
run-name: 'Comment'

on:
  issue_comment:                                     
    types: 
    - created

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  extract:
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'terraform plan')
    runs-on: ubuntu-latest
    outputs:
      workspace: ${{ steps.extract.outputs.workspace }}
      environment: ${{ steps.extract.outputs.environment }}
    steps:
    - name: Extract workspace and environment from comment
      id: extract
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const commentBody = context.payload.comment.body;
          const workspace = commentBody.split(' ')[3].trim();
          const environment = commentBody.split(' ')[2].trim();

          console.log(`Workspace: ${workspace}`);
          console.log(`Environment: ${environment}`);

          core.setOutput('workspace', workspace);
          core.setOutput('environment', environment);

    - name: Show ref
      run: echo ${{ github.event.issue.number }}

    - name: Checkout pull request 🏁
      uses: actions/checkout@v3
      with:
        ref: refs/pull/${{ github.event.issue.number }}/head

    - name: List files
      run: ls

  run-reusable:
    needs:
      - extract
    uses: ./.github/workflows/test-comment-reusable.yml
    with:
      environment: ${{ needs.extract.outputs.environment }}
      workspace: ${{ needs.extract.outputs.workspace }}
      ref: refs/pull/${{ github.event.issue.number }}/head